#!/bin/sh

function loop()
{
	if [ -d "${1}" ]
	then
		for i in "${1}"/*
		do
			loop "${i}"
		done
	fi

	CMD="patchelf --print-rpath --print-interpreter  ${1}"

#	echo "$( patchelf --print-interpreter ${1} )" | grep 'cannot'

	( file "${1}" | grep -q 'ELF' ) && ! ( echo "$( patchelf --print-interpreter ${1} 2>&1 )" | grep 'cannot' -q ) && echo && echo "${CMD}" && ${CMD}
}

loop "${1}"
