#!/bin/sh

function loop()
{
	if [ -d "${1}" ]
	then
		for i in "${1}"/*
		do
			loop "${i}" "${2}" "${3}"
		done
	fi

	CMD="patchelf --set-rpath ${3} --set-interpreter ${2} ${1}"

	( file "${1}" | grep -q 'ELF' ) && ! ( echo "$( patchelf --print-interpreter ${1} 2>&1 )" | grep 'cannot' -q ) && echo && echo "${CMD}" && ${CMD}
}

loop "${1}" "${2}" "${3}"
