#!/bin/bash
declare -A DISC_FLAGS

TMP_FLAGS=${!TMP_FLAGS_NAME}

if [ -z "$TMP_FLAGS" ]
then
	return
fi

TMP_FLAGS_ARRAY=($TMP_FLAGS)

for x in "${!DISCOURAGED_FLAGS[@]}"; do
    DISC_FLAGS[$x]=${DISCOURAGED_FLAGS[$x]}
done

for x in "${!DISC_FLAGS[@]}"
do
	SET_D=${DISC_FLAGS[$x]}

	I_MAX=${#TMP_FLAGS_ARRAY[@]}

	if [[ "${SET_D}" == "+" ]]
        then
            	TMP_FLAGS_ARRAY[$I_MAX]="$x"

		DISC_FLAGS["$x"]=''
        else

		I=0
		while (( $I<$I_MAX ))
	        do
			SET_I=${TMP_FLAGS_ARRAY["$I"]}

	                if [[ "${SET_I}" == "${x}" ]]
	                then
				TMP_FLAGS_ARRAY["$I"]=''
	 			if [ ! -z "$SET_D" ]
				then
					TMP_FLAGS_ARRAY["$I"]="$SET_D"
				fi

	                   unset   DISC_FLAGS["$x"]
	                fi

			let I++
	        done
	fi
done

TMP_FLAGS='';

for (( i=0 ; i<${#TMP_FLAGS_ARRAY[@]} ; i++ ))
do
	#SET=${TMP_FLAGS_ARRAY["$x"]}
	SET=${TMP_FLAGS_ARRAY[@]:$i:1}

	TMP_FLAGS="$TMP_FLAGS $SET"
done

THE_STR="${TMP_FLAGS_NAME}='${TMP_FLAGS}'"

#echo ":::::::::::::::::::::::::::::::::::::::::::::::.."
#echo $THE_STR

eval "$THE_STR"

unset TMP_FLAGS THE_STR DISC_FLAGS TMP_FLAGS_ARRAY;
